[package]
name = "emval"
version = "0.1.0"
authors = ["Hajime Fukuda <hajime.fukuda@me.com>"]

[dependencies]
emval-sys = { git = "https://github.com/hajifkd/emval-sys" }
libc = "*"
lazy_static = "*"

[package.metadata.testjs]
node = "nodejs"
prelude = "tests/prelude.js"
